### ISSUE TITLE
Value is not set correct on submit

### ISSUE THREAD

**Issue by superbilk** [kartik-v/bootstrap-star-rating#10]
Hi, 

after updating to v2, I have the following problem with an Rails 4.1 app:

This is my generated HTML:

``` HTML
<input autofocus="autofocus" class="form-control rating" data-show-caption="false" data-show-clear="false" id="feedback_company_grade" max="5" min="1" name="feedback[company_grade]" type="number" value="4" />
```

When I submit the form, it will send the value twice.

This is what is sent to my app (from chrome inspector):

```
Form data
utf8:✓
feedback[company_grade]:3
feedback[company_grade]:4
feedback[feels_best]:
feedback[change_request]:
button:
```

I don't know where the duplicate value comes from. In v1 (and correctly) there should only one value and it should be 3 -- as 4 is only the preset.

I'd love to add more information if needed. I think the problem might be in the js, but unfortunately I don't know enough about js to debug it.

Best,

Chris

**Comment by apoorv-1310** [comment]
how can i add it to my rails app?
