### ISSUE TITLE
Issue with 4.0.1

### ISSUE THREAD

**Issue by mdjaman** [kartik-v/bootstrap-star-rating#106]
Hi, i recently updated from 3.X to 4.0.1. Got an error in my console and plugin doesn't respond to my settings:
`$('.rating-review').rating({
        displayOnly: true, 
        size: 'xs'
});`

![issue_bootsrap_rating_4_0_1](https://cloud.githubusercontent.com/assets/803262/13372500/31f60d0a-dd3d-11e5-84eb-f0b3bcd0c429.png)

**Comment by kartik-v** [comment]
You do not seem to have the latest version from the `dev-master` of the repo  (OR you have a caching issue on your browser running outdated code). You may want to check that.
