### ISSUE TITLE
Uncaught TypeError: Cannot read property 'html' of undefined

### ISSUE THREAD

**Issue by yigitozkavci** [kartik-v/bootstrap-star-rating#107]
When I hover into my star rating, with every "on" event, this Error occurs on javascript console.

```
Uncaught TypeError: Cannot read property 'html' of undefined

star-rating.js:439
```

**Comment by yigitozkavci** [comment]
This seems to be a bug caused by this setting:
```
showCaption:false
```

**Comment by yigitozkavci** [comment]
This can be solved by changing this
```
if(!self.showCaption) {
    return '';
}
```
to
```
if (!self.showCaption) {
    return self.$caption = $('');
}
```
Because of the fact that .html() cannot be used on neither '' nor undefined, self.$caption must be a jQuery element.

**Comment by kartik-v** [comment]
You do not seem to have the updated code... please update to the latest code from `dev-master`.
