### ISSUE TITLE
Possible Enhancement: Add titles to star elements, like the clear element

### ISSUE THREAD

**Issue by davidklebanoff** [kartik-v/bootstrap-star-rating#111]
Currently the `<div class="clear-rating">` element has a title. Now, since we hit 4.x and stars are now there own individual `<span class="star">` elements, I think it makes since to add titles to these elements for consistency and added accessibility. The titles either being the values of the starCaptions option, or separate options altogether. Whatever approach is taken, I think it should at least be similar to how the clear button's titles and captions are set.

One possibility is to also merge the clear captions and star captions into something like: 

```
{
    0: 'Clear',
    1: 'One Star',
    2: 'Two Stars',
    3: 'Three Stars',
    4: 'Four Stars',
    5: 'Five Stars'
}
```

Thoughts?

**Comment by kartik-v** [comment]
I will look to enhance this - but the clear caption and clear value has to be separate and not mixed with the star captions and values. Note that there is a separate `clearValue` property for this and it can technically be anything what the developer wants (for example even a negative number).
