### ISSUE TITLE
develop to npm

### ISSUE THREAD

**Issue by snowcxt** [kartik-v/bootstrap-star-rating#112]
Could you develop to npm? I can simply run `npm install bootstrap-star-rating`

**Comment by cansin** [comment]
In the meantime you can use `"bootstrap-star-rating": "git://github.com/kartik-v/bootstrap-star-rating#v3.5.5",` to add it to your node project.

**Comment by fsparv** [comment]
Unfortunately, the above advice doesn't help for non-node projects that use npm. (in my case I use https://github.com/craigburke/client-dependencies-gradle, for which bower is not recommended due to api rate limiting at github)

**Comment by kartik-v** [comment]
Done.
