### ISSUE TITLE
Misaligned star with certain min / max settings

### ISSUE THREAD

**Issue by Fuxy22** [kartik-v/bootstrap-star-rating#116]
How to reproduce:

```
$('#rating').rating({
        min: 0.5,
        max: 5,
        step: 0.5
});
```
Will result in something like this:
![star-rating-bug](https://cloud.githubusercontent.com/assets/2676026/13954695/cb56b80a-f039-11e5-8e49-013907d4d3c9.png)

It's probably a floating point math issue.

**Comment by kartik-v** [comment]
No its incorrect config. There are similar queries in the past by others and you need to understand it correctly. The config that you missed is `numStars`. The star highlight will be divided equally based on min, max, step and numStars. The min represents the value when no stars are selected. So if you need min 0.5 and a step of .5 then you cannot have 5 stars getting equally distributed if max is 5...the max has to be 5.5 to divide equally. So set your values as per this. You need to set min to 0 for use case above to get the requirement and add constany value if you need to transform.

**Comment by kartik-v** [comment]
No its an incorrect configuration. There are similar queries in the past by others and you need to understand it correctly. The config that you missed is `numStars`. The star highlight will be divided equally based on `min`, `max`, `step` and `numStars`. The `min` represents the value when no stars are selected. 

- If `min = 0.5`, `max = 5`, `step = 0.5` and `numStars = 5` (the default) -- the values will not get divided equally. Its basically `(max - min) * step / numStars` so basically `(5 - 0.5) * 0.5 / 5` so 45% of each star will be highlighted for every step and not 50% of each star which you want.

So some example options to highlight 50% star with each step are:

- `min = 0`, `max = 5`, `step = 0.5` and `numStars = 5` (the default). The `min  = 0` will mean value when no stars are highlighted

OR

- `min = 0.5`, `max = 5.5`, `step = 0.5` and `numStars = 5` (the default). The `min  = 0.5` will mean value when no stars are highlighted

**Comment by Fuxy22** [comment]
Oh ok then. 

Documentation located at http://plugins.krajee.com/star-rating#option-min is not very clear about that.

> min
> float the minimum value for the rating input. Defaults to 1.

1. Default is incorrect
2. One can assume this could also mean I can set a minimum value for the rating. So for instance if i don't want 0 star ratings

**Comment by kartik-v** [comment]
Yes. The doc will be corrected.

**Comment by kartik-v** [comment]
Yes for 2. For 1, the doc has been corrected.

**Comment by kartik-v** [comment]
Refer the [star highlight logic](http://plugins.krajee.com/star-rating#star-highlight-logic) in documentation.
