### ISSUE TITLE
Smaller scaling for xs

### ISSUE THREAD

**Issue by Disane87** [kartik-v/bootstrap-star-rating#117]
Would it be possible to get all icons and labels much smaller? I've integrated your plugin within Datatables and it too "heavy":
<img width="1329" alt="bildschirmfoto 2016-03-31 um 23 48 35" src="https://cloud.githubusercontent.com/assets/956158/14191983/2715d1ae-f79b-11e5-9f0e-49831520f37b.png">

**Comment by kartik-v** [comment]
You can set size to a value like `xxs` and then define your own CSS styling for that by cross checking with the default CSS.

**Comment by Disane87** [comment]
Thank you. I defined a new class as you mentioned above and it works.
