### ISSUE TITLE
Bootstrap 4 and font-awesome

### ISSUE THREAD

**Issue by epileftro85** [kartik-v/bootstrap-star-rating#118]
Hi, great plugin thank you, i was wondering now the brand new bootstrap 4 doesn't support glyphicon anymore, so i think is good idea migrate to font-awesome or another web font, this is what i made for this, it is just three line:

`filledStar: '<i class="glyphicon glyphicon-star"></i>',`
`emptyStar: '<i class="glyphicon glyphicon-star-empty"></i>',`

to

`filledStar: '<i class="fa fa-star" style="color:#fde16d"></i>',`
`emptyStar: '<i class="fa fa-star"></i>',`

and

`clearButton: '<i class="glyphicon glyphicon-minus-sign"></i>',`

to

`clearButton: '<i class="fa fa-minus-circle"></i>',`

and create a class hide to display none !important because it is not in the bootstrap base

**Comment by kartik-v** [comment]
The docs mention BS 3.x as pre-requisite.

But yes the plugin can be extended... for other CSS frameworks (including BS 4) as you mentioned.
