### ISSUE TITLE
Any possibility to remove border from stars ?

### ISSUE THREAD

**Issue by BenasPaulikas** [kartik-v/bootstrap-star-rating#119]
I would like to make my start look yellow and yellow only, no black border. Any possibility ?

**Comment by kartik-v** [comment]
Create your own theme and CSS... as explained in docs.

**Comment by kartik-v** [comment]
- You can create your own theme ... as explained in docs.

OR

- You can or wrap the star rating in a `<div class="your-custom-class">` and then override the CSS as per your liking based on `your-custom-class`.
