### ISSUE TITLE
Setting star color from attributes or JS

### ISSUE THREAD

**Issue by Aifz** [kartik-v/bootstrap-star-rating#121]
Hey man,

First of all, wanna congratz you about this jquery rating star plugin, this is working nice.
I'd like to customize the star color depending on code-behind values, is there any way I could set an additionnal CSS class or set some data- attributes to get it done ?

Thanks in advance, keep up the good job.

**Comment by kartik-v** [comment]
Yes you should read documentation- you can change the CSS through the `theme` configuration - and you can also augment it with your own custom HTML markup (and CSS) within the `filledStar` and `emptyStar` properties.
