### ISSUE TITLE
How do you make the stars keyboard focusable?  

### ISSUE THREAD

**Issue by bwong199** [kartik-v/bootstrap-star-rating#129]
How do you make the stars keyboard-focusable?

**Comment by dandv** [comment]
Accessibility is not one of the features of this plugin. Check out [starability](https://github.com/LunarLogic/starability/) instead, but beware of [this issue](https://github.com/LunarLogic/starability/issues/15).

**Comment by kartik-v** [comment]
Will look into an enhancement for accessiblity when I get time. Feel free to submit a PR though.
