### ISSUE TITLE
Feature Request: Any chance we can get this on Bootstrap 4?

### ISSUE THREAD

**Issue by davidpanzarella** [kartik-v/bootstrap-star-rating#138]

**Comment by kartik-v** [comment]
Though, not tested for BS4 (as its not stable yet)... it should still work with a bit of configuration from your side - similar to how you use the font awesome theme as described in the demos.

**Comment by davidpanzarella** [comment]
@kartik-v I did get it to work in the end by modifying the source a bit. Looking forward to seeing the updates though! Thanks for the reply!

**Comment by kartik-v** [comment]
You may not need to modify the source as these will get changed with updates. Recommend to use the theme property to override your styling...  Or Even use it without bootstrap.
