### ISSUE TITLE
Locale not working

### ISSUE THREAD

**Issue by roke22** [kartik-v/bootstrap-star-rating#141]
Hello,

I am using this plugin and works like a charm, is very nice but the locales are not working.

I have included the js files:

<script src="../../plugins/stars-rating/js/star-rating.js" type="text/javascript"></script>
<script src="../../plugins/stars-rating/js/locales/es.js" type="text/javascript"></script>

And i initilize with this:
$("#starsrating").rating();

Should i pass a parameter? is not working or did something wrong?

Best Regards.

**Comment by kartik-v** [comment]
You may want to check the documentation. You need to set the [language](http://plugins.krajee.com/star-rating#option-language) property of the plugin to the language iso code. In addition, you may want to check the [guidelines for creating translations](http://plugins.krajee.com/star-rating#translations) in case your locale file does not exist. Check [the usage](http://plugins.krajee.com/star-rating#usage) on how you must load the translation JS files.

**Comment by roke22** [comment]
OK, but can you tell me how to do it? I can not find any example in the documentation.
Have to be like this?
$("#starsrating").rating("es");

**Comment by kartik-v** [comment]
You surely seem to have not gone through the [docs](http://plugins.krajee.com/star-rating) and [demos](http://plugins.krajee.com/star-rating/demo). The usage is like any other jquery plugin.

Check [advanced demo example # 8](http://plugins.krajee.com/star-rating-demo-advanced-usage#advanced-example-8).

If you need programming help please use the [webtips forum](http://webtips.krajee.com/questions). This repo is only for raising issues/enhancements.

**Comment by jcarlos37** [comment]
I used these parameters:

```
StarRating::widget([
		'name' => 'rating_article',
		'value' => 3,
		'language' => 'es',
		'pluginOptions' => [
				'size' => 'xs',
				'language' => 'es',
		],
]);

```
But did not work.

Finally, I need to fix the file vendor\kartik-v\yii2-widget-rating\StarRating.php (version 1.0.2), the line 60 was replaced:

```
//StarRatingAsset::register($view)->addLanguage($this->language, 'star-rating_locale_'); //Old Line
StarRatingAsset::register($view)->addLanguage($this->language, null, 'js/locales'); //New Line

```
