### ISSUE TITLE
Can't scroll on mobile devices

### ISSUE THREAD

**Issue by dmitri-wm** [kartik-v/bootstrap-star-rating#142]
On mobile devices, I can't scroll if touch is started on the star event even if it's read-only
This is because _listenClick method makes preventDefault. This shouldn't be done if control is read-only or disabled

**Comment by dandv** [comment]
Saw the same problem on Chrome 55 on Android 7.

**Comment by kartik-v** [comment]
Resolved via cb0caa1.

**Comment by DanjBethel** [comment]
Can anyone verify that this was fixed? Using latest version and for some reason having this exact same issue
