### ISSUE TITLE
Probleme Mvc Project Usage

### ISSUE THREAD

**Issue by Milad-Darvishi** [kartik-v/bootstrap-star-rating#146]
Hello,
When I Return Partial From Action Method With RenderPartial() script Not Implimenting On Form.
How Can I Fix it?

**Comment by dandv** [comment]
Please use normal capitalization.

**Comment by FreakyBoy** [comment]
I used Zend Framework 2 (MVC) and all working fine :) with a "renderPartial" Methode or directly in the view.
