### ISSUE TITLE
Please list the plugin size

### ISSUE THREAD

**Issue by dandv** [kartik-v/bootstrap-star-rating#151]
Minified and gzipped.

**Comment by kartik-v** [comment]
Plugin size depends on what functionality you need... its a bit modular..

you can get it by looking here:

- [The basic JS script star-rating.min.js](https://github.com/kartik-v/bootstrap-star-rating/blob/master/js/star-rating.min.js)
- [The basic styling CSS star-rating.min.css] [star-rating.min.js](https://github.com/kartik-v/bootstrap-star-rating/blob/master/css/star-rating.min.css)

The other files are optional based on your need... like 
- including locales if you need transaltions
- including theme files if you need themes
