### ISSUE TITLE
Possible Enhancement or Styling change request

### ISSUE THREAD

**Issue by dbd5** [kartik-v/bootstrap-star-rating#158]
## Prerequisites

- [YES ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [YES ] The issue still exists against the latest `master` branch of bootstrap-star-rating.
- [ YES] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/star-rating) and [demos](http://plugins.krajee.com/star-rating/demo).
- [YES ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [YES] I have attempted to find the simplest possible steps to reproduce the issue.
- [ NO] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.Add the star rating to a form
2.Place a DIV with some number after the star rating
3.Per display block CSS, the new div is rendered in a new line 

## Expected behavior and actual behavior

When the star rating value is aggregated from a number of reviews, it makes sense to place that information alongside the star rating control because the number of reviews makes the rating more meaningful. (An item with 4 stars from 2,900 reviews is probably better than a similar item with 5 stars from 3 reviews)
 
I will like to place the number of reviews immediately after the star rating (not on a different line) to provide this additional insight to the user. Any suggestion for CSS modification to achieve this or will it be better to modify the star rating control to include a callback that the developer can code to count the number of raters?

Regards,

Adam

**Comment by dbd5** [comment]
Hi @kartik-v 

The following CSS works fine, I'm wondering if it won't break anything I'm not aware of in terms of how you place and style the stars

.rating-container {
    display: inline !important;
}

**Comment by kartik-v** [comment]
> I will like to place the number of reviews immediately after the star rating (not on a different line) to provide this additional insight to the user. Any suggestion for CSS modification to achieve this or will it be better to modify the star rating control to include a callback that the developer can code to count the number of raters?

You can achieve this through simple HTML markup as well, either using `float: left` on the div OR using a tabular layout... and use bootstrap like grid system to show contents side by side.

If you are keen on changing the styles you can use the theming functionality.
