### ISSUE TITLE
Scrolling page can cause rating to adjust

### ISSUE THREAD

**Issue by JWess** [kartik-v/bootstrap-star-rating#167]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of bootstrap-star-rating.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/star-rating) and [demos](http://plugins.krajee.com/star-rating/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Put one or more of this plugin on a scrollable webpage.
![image](https://user-images.githubusercontent.com/8697891/28595871-eae49b04-7163-11e7-8ec3-e89bfe716c03.png)

2. On a mobile device, attempt to scroll the page up/down with swipes beginning on the stars.

## Expected behavior and actual behavior

When I follow those steps, I see...
The star rating adjusts.

I was expecting...
The page to scroll without adjusting the star rating. As you can see in the screenshot, a lot of the screen is covered by instances of this plugin, which means the user is very likely to bump them when attempting to scroll the page. Other elements on a page (buttons, checkboxes, inputs, etc) do not have to be avoided when scrolling, thus this one shouldn't be either.

## Environment
iPhone 6

Browsers
- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [X] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [X] Mobile

Libraries

- jQuery version: v3.2.1
- bootstrap-star-rating version: 4.0.1

## Isolating the problem

- [X] This bug happens [on the plugin demos page](http://plugins.krajee.com/star-rating/demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-star-rating without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
I am open to suggestions. But I feel you would need to use a CSS styling as per your device needs. For example padding your containers for scrolling and having smaller style stars.

**Comment by JWess** [comment]
Is there any way for the plugin to pay closer attention to the direction/speed of the swipe? If the stars are laid out in a horizontal direction, it seems like a vertical swipe shouldn't affect them.

**Comment by kartik-v** [comment]
its not swipe but a click on the screen which you cannot control... imagine a checkbox on a screen and you start your swipe from the checkbox...
