### ISSUE TITLE
Unable to rate with star 0

### ISSUE THREAD

**Issue by Priyank780** [kartik-v/bootstrap-star-rating#168]
As you are allowing user to rate from 1 to 5 and select 'Not Rated' but what if user want to select star 0 (zero). Is it possible with existing code? I tried with giving min value -1 but it is not working.

Here is my html code,

<label for="star" class="control-label">Rate This</label>
<input type="number" id="star" name="star[1]" class="rating rating-loading" data-min="0" data-max="5" data-step="1" value="1" data-size="xs">

I asked the same question on comment section, but I didn't get any reply from there. http://plugins.krajee.com/star-rating/demo#comment-3452935989

**Comment by kartik-v** [comment]
This is [answered on the forum](http://plugins.krajee.com/star-rating/demo#comment-3469340173)
