### ISSUE TITLE
using bootstrap-star-rating in Vue, I got this error : Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by bohehe** [kartik-v/bootstrap-star-rating#169]
## Cannot read property 'fn' of undefined
When using bootstrap-star-rating in Vue, I got this error after I import star-rating.min.js
"Uncaught TypeError: Cannot read property 'fn' of undefined"
so odd... I'm using Vue v2.8  and  bootstrap-star-rating v4.0.2

**Comment by bohehe** [comment]
I use `npm install bootstrap-star-rating --save` to install, and the error msg disappeard...

**Comment by DuudeXX8** [comment]
same trouble
