### ISSUE TITLE
Uncaught TypeError: $(...).rating is not a function

### ISSUE THREAD

**Issue by RoRElessar** [kartik-v/bootstrap-star-rating#172]
I've installed the plugin via bower and included it into bower.json file: `bower install bootstrap-star-rating --save` In the view (it's a Rails project) I have this piece of code: 

```
<%= form.text_field :rating,
                            id: :review_rating,
                            class: 'form-item large-6 cell',
                            placeholder: 'Rating*',
                            required: true %>
```

and in js: 

```
$('#review_rating').rating({
		min: 1,
		max: 5,
		step: 1,
		size: 'sm',
		theme: 'krajee-uni'
	});
```
Why am I getting the error: `Uncaught TypeError: $(...).rating is not a function`, if plugin is present in `bower.json` as a dependency?

**Comment by kranthi23** [comment]
I am also getting same error.
Like: Uncaught TypeError: $(...).rating is not a function
how to  resolve it??

**Comment by lihua123569** [comment]
me too

**Comment by JunaidZaheerKhan** [comment]
me too

**Comment by JunaidZaheerKhan** [comment]
why please help
Uncaught TypeError: $(...).rating is not a function #193
