### ISSUE TITLE
Why always showing loading icon, not showing the star

### ISSUE THREAD

**Issue by ruchin96** [kartik-v/bootstrap-star-rating#174]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-star-rating.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/star-rating) and [demos](http://plugins.krajee.com/star-rating/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-star-rating version:

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/star-rating/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-star-rating without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by ruchin96** [comment]
Why cannot showing star,

echo StarRating::widget(['name' => 'flaticon-star129','value' => $totalRating, 'pluginOptions' => [
                                            'displayOnly' => true, 
                                            'step' => 0.1, 
                                            'size'=>'xs',
                                         ]]);

**Comment by ruchin96** [comment]
echo StarRating::widget(['name' => 'flaticon-star129','value' => $totalRating, 'pluginOptions' => [
                                            'displayOnly' => true, 
                                            'step' => 0.1, 
                                            'size'=>'xs',
                                         ]]);

**Comment by kia1349** [comment]
i have same problem
