### ISSUE TITLE
Added non-passive event listener

### ISSUE THREAD

**Issue by izemize** [kartik-v/bootstrap-star-rating#175]
Hi

I have flowing warns on console:

Added non-passive event listener to a scroll-blocking 'touchmove' event.
Added non-passive event listener to a scroll-blocking 'touchstart' event

triggers by star-rating.js:62

**Comment by OstrikovG** [comment]
I have the same problem 
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. 

add @ jquery.min.js:3
(anonymous) @ jquery.min.js:3
each @ jquery.min.js:2
each @ jquery.min.js:2
ya @ jquery.min.js:3
on @ jquery.min.js:3
handler @ star-rating.min.js:10
_listen @ star-rating.min.js:10
_init @ star-rating.min.js:10
a @ star-rating.min.js:10
(anonymous) @ star-rating.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
e.fn.rating @ star-rating.min.js:10
(anonymous) @ (index):790

**Comment by OstrikovG** [comment]
`
add @ jquery.min.js:3
(anonymous) @ jquery.min.js:3
each @ jquery.min.js:2
each @ jquery.min.js:2
ya @ jquery.min.js:3
on @ jquery.min.js:3
handler @ star-rating.min.js:10
_listen @ star-rating.min.js:10
_init @ star-rating.min.js:10
a @ star-rating.min.js:10
(anonymous) @ star-rating.min.js:10
each @ jquery.min.js:2
each @ jquery.min.js:2
e.fn.rating @ star-rating.min.js:10
(anonymous) @ (index):790
`
