### ISSUE TITLE
Allow select instead of input as fallback

### ISSUE THREAD

**Issue by dereuromark** [kartik-v/bootstrap-star-rating#178]
In my case the application uses a dropdown select with 1, 2, 3, 4, 5 to choose from as fallback.
In case the JS cannot be loaded or has an error, you can at least select from that dropdown list and post.

However, this script seems to only work with input.
I hacked it in with
```js
		$('#star-wrapper').on('rating:change', function(event, value, caption) {
			$('#star-element').val(value);
		}).hide();
```
But maybe it could auto-find the type of form input and in case of select handle it natively.
Of course those values must then always match 1:1, in case you are not having step 1, but step 0.5, it would need to have all those in between too. but that is responsibility of the select then, not this script :)

Just handling it without the need of a custom callback would be nice.

**Comment by Bhoft** [comment]
Maybe a html5 input type number should be used instead of the text input field. 
Then if there is an JS error or the JS is not loaded you would still have the rating with min, max and steps options.

**Comment by dereuromark** [comment]
Fine by me :)

**Comment by kartik-v** [comment]
Yes the `input type=number` is a good fallback option when JS is disabled, and will default the min, max, step attributes from the input into the plugin. The only thing as mentioned in the user guide (and referred by Bhoft earlier) - read about the number input issue when you have decimals or fractional rating values. A `select` style input is not in the scope of the plugin currently.

**Comment by dereuromark** [comment]
I am just saying that I use a select, as it has to be pre-defined choices here :)
So allowing the script to work with such an element would be great. I hacked it for now, though.
See http://sandbox.dereuromark.de/sandbox/ratings
