### ISSUE TITLE
New Font Awesome version (5.x) breaks empty star

### ISSUE THREAD

**Issue by Hannoma** [kartik-v/bootstrap-star-rating#181]
The value for an empty star in the Font Awesome theme is 'fa fa-star-o' but in the new version of Font Awesome (5.0.0) the empty star was renamed to 'fa**r** fa-star'. (https://fontawesome.com/icons/star?style=regular)

**Comment by kartik-v** [comment]
You need to configure these properties specific to your icon markups for example.. .font awesome 5. Maybe a theme can be added for font awesome 5 later (and probably included with the plugin).

**Comment by kartik-v** [comment]
There is a new font awesome 5.x theme `krajee-fas` 

[Check the demo](http://plugins.krajee.com/star-rating-demo-theme-fas).
