### ISSUE TITLE
Some dots appear below the stars after click

### ISSUE THREAD

**Issue by Daemoonn** [kartik-v/bootstrap-star-rating#184]
![image](https://user-images.githubusercontent.com/17616657/38868478-b592d8fc-4279-11e8-828c-c13ce09eff84.png)

http://plugins.krajee.com/star-rating-demo-basic-usage

In my chrome browser, some dots appear under the stars after my click, and of course they appear in my code too. I think it's maybe the head of the decimal. I suggest that the default usage is better to be something like

`<input type="hidden" id="input-2" name="input-2" class="rating rating-loading" data-min="0" data-max="5" data-step="0.1">`

Add `type="hidden"` to clear the dots.

**Comment by kartik-v** [comment]
The input is purposely not hidden (via the `type` or the `style`) - to allow `required` attribute validation by the browser. This can be seen in  [basic demo # 9](http://plugins.krajee.com/star-rating-demo-basic-usage#basic-example-9). This is being updated with a fix.
