### ISSUE TITLE
Not working with boostrap 4.1.1

### ISSUE THREAD

**Issue by mianaliasjad** [kartik-v/bootstrap-star-rating#185]
I am trying to use it on bootstrap 4 but unfortunately is not working.

**Comment by kartik-v** [comment]
Note that Bootstrap 4 does not have bundled glyphicons anymore unlike BS3.

Check the plugin docs and demos for BS4 usage

- Option 1: You can use relevant theme - Font Awesome or Krajee Unicode Icons or SVG theme of the plugin to render those icons
- Option 2: You can load glyphicons on your page separately assuming you have the right license - and the defaults will work.
