### ISSUE TITLE
Displayonly disables the caption and therefore the value could only be guessed (reopen)

### ISSUE THREAD

**Issue by Bhoft** [kartik-v/bootstrap-star-rating#188]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-star-rating.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/star-rating) and [demos](http://plugins.krajee.com/star-rating/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

This is a issue is still existing 
https://github.com/kartik-v/bootstrap-star-rating/issues/177

Thanks for adding the display caption as title mode but there is still one issue.
In my code I have the possibility to show the caption as a title, so you see the current value on hover.
But also (and this isn't possible in your version) show the caption as well.

This is needed e.g. if you create a pdf from the html code and the value of the rating is not integer but some decimal value (like 3.4 of 5).
With only the "stars" it is not correctly visible if the rating is 3.4 or 3.5 or ..

So it should be possible to also print out the caption the same way as the rating shows in input mode.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting to have enable also the caption.
![image](https://user-images.githubusercontent.com/1777147/45680313-e50afd00-bb3a-11e8-93b1-b06d8c562021.png)

But even if i enable it by `showCaption => true` it is disabled by your displayOnly mode.
https://github.com/kartik-v/bootstrap-star-rating/blob/67b2fbcb2d1a42a843d6798c7078c4f776d75664/js/star-rating.js#L256-L259

You shoudn't set showCaption to false automatically when displayOnly mode is enabled.

**Comment by kartik-v** [comment]
Resolved via [update to release v4.0.5](https://github.com/kartik-v/bootstrap-star-rating/commit/7b48a78bda1ded89a55790f4f65bb50c670653d7).
