### ISSUE TITLE
problem with last Jquery version

### ISSUE THREAD

**Issue by matala22** [kartik-v/bootstrap-star-rating#191]
In the documentation it is reported that:
Pre-requisites
    Latest JQuery
(<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.js"></script>)

But with jQuery 3.3.1
(<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.js"></script>)
the stars disappear

**Comment by mashgreat2** [comment]
I also can not get it to work. The stars won't show.

**Comment by kartik-v** [comment]
> Apparently, stars won't show if you use latest bootstrap css

Understand the dependencies - when you say latest bootstrap - you are using Bootstrap 4.x which does not have GLYPHICONS bundled unlike Bootstrap 3.x - so the default Glyphicon star will not be rendered for Bootstrap 4.x unless you load the glyphicons css. For Bootstrap 4.x you can alternatively use other themes like SVG, Unicode, or Font Awesome to load your star icons.
