### ISSUE TITLE
Enhancement: StarCaptionClasses CSS classes by Percentage width

### ISSUE THREAD

**Issue by Bhoft** [kartik-v/bootstrap-star-rating#194]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-star-rating.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/star-rating) and [demos](http://plugins.krajee.com/star-rating/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

Just an enhancement which I have added by Pull request some time ago ( 26 Mar 2018)
https://github.com/kartik-v/bootstrap-star-rating/pull/180

Would it be possible to change the star-rating.js by changing those lines so it would be possible to e.g. set the CSS Caption classes by the width percentage?

e.g. I have a variable rating one rating goes from 1-5 and another 1-10.
but the Label CSS classes should be the same which could be easily done by the width percentage.

I have used the rating plugin for some reviewing where the Organizer could change the rating settings themself and differently for multiple categories which they can add. So it would be good if this kind of Label class setting could be done by percentage and not only by the values.

**Comment by kartik-v** [comment]
Resolved via [update to release v4.0.6](https://github.com/kartik-v/bootstrap-star-rating/commit/cb449271f24c78ab54726232daf5b9dae3e49dbd).
