### ISSUE TITLE
Update package.json for Bootstrap 4 Support

### ISSUE THREAD

**Issue by mc962** [kartik-v/bootstrap-star-rating#195]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-star-rating.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/star-rating) and [demos](http://plugins.krajee.com/star-rating/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue

1. Install using one of the 2 popular node package managers with commands `yarn install` or `npm install` (I used yarn), or check the packages using `yarn check`. You will likely get some error output when finished (although these are more warnings).

## Expected behavior and actual behavior

When I follow those steps, I see an error message outputted such as `error "bootstrap-star-rating#bootstrap@~3" doesn't satisfy found match of "bootstrap@4.2.1"` (although this does not prevent install). This is using the `yarn` package manager, but I would expect the `npm` package manager to give a similar message.

I was expecting this message not to appear, as it seems as if this package has had bootstrap 4 support since `v4.0.4`. From what I can see, it just seems like the `package.json` file was not updated to include support for the newer bootstrap version.

## Environment

Operating System

- [x] Mac OS X

Libraries

- jQuery version: 3.3.1
- bootstrap-star-rating version: 4.0.4

## Isolating the problem

This bug is mainly a package an outdated package management file problem, where the supported Bootstrap version on the `package.json` file needs to be updated to (or add support for) Boostrap 4.x. This is assuming that the package is ready for a change to the requirements like this. I assumed that it was, after reading both the release comments, and using it with Bootstrap 4, but I'm not aware of any other reasons why it may not have been upgraded to the newer version in the package.json file.

**Comment by kartik-v** [comment]
Resolved via [update to release v4.0.6](https://github.com/kartik-v/bootstrap-star-rating/commit/cb449271f24c78ab54726232daf5b9dae3e49dbd).
