### ISSUE TITLE
Events are being called multiple time

### ISSUE THREAD

**Issue by Doopin** [kartik-v/bootstrap-star-rating#197]
I have found 2 similar issues not resolved yet but please excuse of adding adding mine as there is a slight difference.
Am using the version v4.0.5 with JQuery 3.1.1.
I have initialized the plugin after calling livequery plugin [(from this author Brandon Aaron)]( http://brandonaaron.net) as my star rating input is added on demand when the DOM is already initialized
The whole thing works great with the only exception that events get called so many time. And the number of time they get triggered keeps increasing on the same element when the user interacts with (See the image below).
Please any idea on what could be the reason of this? Any fix?

![imgcap](https://user-images.githubusercontent.com/10206793/57007707-006ada00-6beb-11e9-969c-23c19a581ca9.PNG)

Script used: 
`$('.langLevel').livequery(function() {
        $('#langLevel0').rating({
            step: 1,
            min: 0,
            max: 5,
            size: 'sm',
            theme: 'krajee-fa',
//            clearButton: '',
            captionElement: "",
            showCaptionAsTitle: false, 
            starCaptions: {1: 'Beginner', 2: 'Intermediate', 3: 'Advanced', 4: 'Proficient', 5: 'Native'},
            starCaptionClasses: {1: 'text-danger', 2: 'text-warning', 3: 'text-info', 4: 'text-primary', 5: 'text-success'}
        }).on("rating:clear", function(event) {
            console.info("Your rating is reset");
        }).on("rating:change", function(event, value, caption) {
            console.info("You rated: " + value + " = " + $(caption).text());
        });
    }, function() {
        // unmatchFn
        return;
    });`

Thank you in advance for your assistance

**Comment by kartik-v** [comment]
It seems you are registering the plugin multiple times with your third party script - resulting in duplication of events. Either do a proper `destroy` and reinitialize the plugin - else check the third party script to avoid this issue.
