### ISSUE TITLE
Using Bootstrap 4 it half works: "starts" are not visible

### ISSUE THREAD

**Issue by palminha** [kartik-v/bootstrap-star-rating#198]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-star-rating.
- [X] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/star-rating) and [demos](http://plugins.krajee.com/star-rating/demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Install with composer as instruction on readme

## Expected behavior and actual behavior

When I follow those steps, I don't see the starts.
I can see the "Not Rated" and if i over the mouse close the caption i see it changing to "One Star", "Two Stars", etc... but the stars are not visible.

I was expecting the stars to be visible

## Environment

Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1-min
- bootstrap-star-rating version: 4.0.6
- laravel: 5.8.23
- bootstrap: 4.1.3

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/star-rating/demo)
- [ ] The bug happens consistently across all tested browsers
- [X] This bug happens when using bootstrap-star-rating without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by palminha** [comment]
Tried out what is described here #196 and it doesn't work

**Comment by mhnamaki** [comment]
Have you found a solution? :)

**Comment by Wagnerxyz** [comment]
you should set theme property! `  $("#input-id").rating({ theme: 'krajee-svg'});`

**Comment by kartik-v** [comment]
By default the plugin uses `krajee-svg` theme since the latest releases (as Bootstrap 4.x and 5.x are out and they do not support glyphicons). Remember you need to load the `krajee-svg` theme assets (js/css) on your page as well.

**Comment by kartik-v** [comment]
By default the plugin has been updated since v4.1.0 to use `krajee-svg` as the default theme. This is because plugin has moved more towards support of Bootstrap later releases like 4.x and 5.x and both these releases do not support glyphicons. Remember you need to load the `krajee-svg` theme assets (js/css) on your page as well as mentioned in the [usage section of the docs](https://plugins.krajee.com/star-rating#usage).

**Comment by luoxiangyu02** [comment]
i meet the same question ,have you found a solution?
