### ISSUE TITLE
defaults language unable to set

### ISSUE THREAD

**Issue by czy-1** [kartik-v/bootstrap-star-rating#206]
Hello,

I am using this plugin, is very nice but the defaults language unable to set.

I have included the js files:

<script src="../../plugins/stars-rating/js/star-rating.js" type="text/javascript"></script> <script src="../../plugins/stars-rating/js/locales/zh.js" type="text/javascript"></script>
And i set with this:
$.fn.rating.defaults.language = 'zh';

I want to set the default language to zh, but it not work.

How should I set the default language?

jQuery version:: 3.1.1
bootstrap-star-rating version: 4.0.6

Best Regards.

**Comment by kartik-v** [comment]
Just set the plugin's [`language`](https://plugins.krajee.com/star-rating/plugin-options#language) property.
```js
$('#ratingInputId').rating({
    language: 'zh'
});
```
