### ISSUE TITLE
Module handling seems wrong

### ISSUE THREAD

**Issue by ittayd** [kartik-v/bootstrap-star-rating#215]
The module wrapping checks if module.exports is defined and if so assigns to it the result of the factory function. But this function doesn't have a return value, so module.exports ends up being undefined.

**Comment by ittayd** [comment]
Also, themes ignore any module system and use window.jQuery directly.

**Comment by kartik-v** [comment]
Thanks. Will check when I get time. Appreciate if you can submit a PR enhancement.
