### ISSUE TITLE
filling one star or icon instead of all previous ones

### ISSUE THREAD

**Issue by khaledmndev** [kartik-v/bootstrap-star-rating#222]
- This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/star-rating) and [demos](http://plugins.krajee.com/star-rating/demo).

let's say i have 5 stars or 5 icons, and i want to highlight/pick the 3rd start only instead of filling the 1st and 2nd stars.. is this option available in this plugin? thanks..

Browsers
Edge (Chromium)

Operating System
 Windows 11

Libraries

- jQuery version: v3.6.0
- bootstrap-star-rating version: v4.1.0

**Comment by kartik-v** [comment]
You need to set the [`minThreshold`](https://plugins.krajee.com/star-rating/plugin-options#minThreshold) property for your use case -- read docs.

There is also the [`min`](https://plugins.krajee.com/star-rating/plugin-options#min) property.
