### ISSUE TITLE
Font-awesome instead of glyphicons

### ISSUE THREAD

**Issue by LeleDev** [kartik-v/bootstrap-star-rating#37]
Is it possibile to use font-awesome instead of glyphicons?

If not, do you plan to add this feature in the future?

Thank you in advance

**Comment by kartik-v** [comment]
Check the updated latest release v3.5.1 which has enhancements for other icon font libraries with clear [instructions and examples](http://plugins.krajee.com/star-rating/demo#advanced-usage) for integrating with font awesome.
