### ISSUE TITLE
No correct POST values on mobile devices

### ISSUE THREAD

**Issue by Stefannno** [kartik-v/bootstrap-star-rating#45]
Hello,

When I create a simple page with a star rating and submit the form, I get the correct (POST) results on my pc. When I use the same page on a mobile device (iOS 8.3) I only get value 0 from the star rating.

I'm using star rating version 3.5.1.
Mobile browser: Safari, Chrome (41.0.2272.58)
PC browser: Chrome (41.0.2272.118), IE 11 (11.0.9600.17690)

PC output:
![pcrating](https://cloud.githubusercontent.com/assets/11956376/7153414/7333a42c-e34b-11e4-8edc-d9eda9cc2d72.png)

Mobile output:
![mob1](https://cloud.githubusercontent.com/assets/11956376/7153486/a0892914-e34c-11e4-85ea-e1a3932af4f2.png)

The error occurs in the following code (file name: starrating.php):

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Krajee JQuery Plugins - &copy; Kartik</title>
    <link rel="stylesheet"  href="http://netdna.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="../css/star-rating.css" media="all" rel="stylesheet" type="text/css"/>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="../js/star-rating.js" type="text/javascript"></script>
</head>
<body>
<div class="container">
    <?php
    if(isset($_POST['testform'])){
        print_r($_POST);
        echo "<br />";
    }
    ?>
    
<form method='POST' action='starrating.php'>
    <input id="TEST" name='stars' value="0" type="number" class="rating" data-symbol="" min=0 max=5 step=1 >
    <br /><br />
    <input type='hidden' name='testform' value='1' />
    <input type='submit' value='Submit'>
</form>
</div>
</body>
</html>

**Comment by Stefannno** [comment]
Is there a solution for this? It seems the form is reloaded/refreshed on submit. I can't find a solution for this on the internet.

**Comment by kartik-v** [comment]
Not sure of your mobile browser support. Change the input type to `text` and try... instead of input type `number`.

**Comment by Stefannno** [comment]
When I change it to text and in the form put for example 3 in the text field and submit, it works.

**Comment by kartik-v** [comment]
I am not saying that... in your example above... use input type = text instead of input type = number to initialize the rating...

**Comment by Stefannno** [comment]
I think you mean: 
< input id="TEST" name='stars' value="0" type="text" class="rating" data-symbol="" min=0 max=5 step=1 >
?

**Comment by kartik-v** [comment]
And I see that you have entered a blank `data-symbol` you may want to remove that.

**Comment by kartik-v** [comment]
If you are using with input type = `text`... I would suggest you change `min` to `data-min`, `max` to `data-max` and `step` to `1`.

And I see that you have entered a blank `data-symbol` you may want to remove that.

**Comment by Stefannno** [comment]
Unfortunately still no luck. On submit the form is refreshed and after it is posted with all 0 values.

**Comment by kartik-v** [comment]
Try to use events to debug... where the issue is:

Here are the [events offered by the plugin](http://plugins.krajee.com/star-rating#events). Initialize each of these events and try to read your input value (for example on change and then on form submit) etc.

**Comment by Stefannno** [comment]
OK thank you I will try. Do you use the star rating on your own website so I can test it with my phone? On the demo page I see no version with a submit button that will show me the post results.

**Comment by kartik-v** [comment]
This is due to a problem of `click` event not detected on certain mobile devices. Will provide an enhancement.
