### ISSUE TITLE
Love it... but the example

### ISSUE THREAD

**Issue by davidrenne** [kartik-v/bootstrap-star-rating#49]
Man I love it, but man you really need to show the examples with min=0 and max=5.

It is all wrong and you have not verified the examples out on:

http://www.jqueryscript.net/other/Simple-jQuery-Star-Rating-System-For-Bootstrap-3.html

Please update this.  I had to spend extra time doing through getValueFromPosition() to realize that your example isnt right for five stars and is setting the width as 25% when it should be min=0 which will calculate correctly with the CSS.

Also it would be nice to have some caller examples without the class of "rating" and with examples of callbacks on rating change because that is the most important one to APIing to the data layer from the javascript widget:

```

  <script>
    $(document).ready(function () {
        var $input = $('#rating-system'), count = Object.keys($input).length;
        if (count > 0) {
            $input.rating({
              min: 0,
              max: 5,
              step: 1,
              size: 'custom'
            });

            $('#rating-system').on('rating.change', function(e){
              console.log($(e.target).val());
            });
        }

    });
  </script>
```

**Comment by davidrenne** [comment]
Now I am reading your github docs  which have some better examples.

Update jquery site because that is what has a higher page rank than the github

**Comment by kartik-v** [comment]
The site link mentioned is not at all maintained by me or officially related to the extension. The official docs and demo page is at [Krajee Plugins](http://plugins.krajee.com/star-rating).

**Comment by davidrenne** [comment]
Yea that is fine, but it gets higher in page rank so that is where your
users first might go.
