### ISSUE TITLE
in jquery on click function i need to disable star rating ( i need to do like toggle)

### ISSUE THREAD

**Issue by RajMondaz** [kartik-v/bootstrap-star-rating#51]
how to do this
1.intially if i set the value data-readonly="true"  it is working fine but if i am doing it in jquery it is not working how to fix it..

**Comment by kartik-v** [comment]
[Read documentation](http://plugins.krajee.com/star-rating). You need to use plugin's [refresh method](http://plugins.krajee.com/star-rating#method-refresh) after setting the readonly property.
