### ISSUE TITLE
How can i apply required for rating

### ISSUE THREAD

**Issue by RajMondaz** [kartik-v/bootstrap-star-rating#52]
i need a rating as mandatory field how to achieve this.

**Comment by kartik-v** [comment]
Use your own javascript or server (PHP) code to validate on form submit or similar methods where you validate the rating submission... 

Many MVC frameworks have this as a pre-built input validation method.

**Comment by s1mp1c** [comment]
In case you use HTML5 validation messages for all the inputs of a form, in my opinion is not a good idea to use a different error message layout only for the star rating input. I think you could improve your plugin adding the faculty to set "required" as attribute, so HTML5 will do the rest.

**Comment by kartik-v** [comment]
As I mentioned there is nothing specific to add from the plugin side... you can go ahead and add the required attribute to the input. HTML5 will do its validation if you are using a form to submit. However not sure if it does validation on hidden inputs.

In the end you as a developer need to still validate WHEN you want it required? This is dependent on your application design - whether after saving a form, OR whether after you capture the rating OR Whenever.

**Comment by kartik-v** [comment]
As I mentioned there is nothing specific to add from the plugin side... you can go ahead and add the required attribute to the input. HTML5 will do its validation if you are using a form to submit. However not sure if it does validation on hidden inputs.

In the end you as a developer need to still validate WHEN you want it required? This is dependent on your application design 

- whether after saving a form, 
- OR if you do not have a FORM - whether after an ajax update 
- OR whether after you capture the rating 

etc..

**Comment by s1mp1c** [comment]
hidden attribute inhibits required attribute, so HTML5 validation doesn't work on it.
In my case i have a form with 2 inputs: star rating and text area.
Anyway since your plugin uses hidden attribute, there is nothing that we can do to use HTML5 validation messages.
Thank you anyway for your great support ;)

**Comment by ZexusUE4** [comment]
I have managed to workaround the this, you can add the html5 required attribute then use the on change method to remove that required prop so the html5 validation won't pop up again.
` <input class="rating rating-input" oninput="this.setCustomValidity('')" oninvalid="this.setCustomValidity('Please select a rating')" required="true" type="text" value="0">

 $('.rating').on('change', function () {
            this.setCustomValidity('');
            $(this).removeAttr('required');
            $(this).removeAttr('oninvalid');
        });`
