### ISSUE TITLE
How can change ID of input element.

### ISSUE THREAD

**Issue by JamesBarnsley** [kartik-v/bootstrap-star-rating#53]
Hi,
I have put the ID in like this ...
"id" => "profileskill-rating-" . $id
It changes the JS ID but not the input ID. Is there anyway to change the input ID. The reason I am asking is because I want two on a page and I want to do it through PHP and not use the JQuery manually.
Any ideas?

**Comment by kartik-v** [comment]
Not clear of your query -- you set the input element ID attribute.

If you are talking about [Yii StarRating widget](http://github.com/kartik-v/yii2-widget-rating)  then this is the wrong repo. You can set input id via `options => ['id' => 'your-id']`.
