### ISSUE TITLE
Rating shown two times

### ISSUE THREAD

**Issue by s1mp1c** [kartik-v/bootstrap-star-rating#54]
Sorry for cross-posting but none was able to help me.
Can you tell me what's wrong at this?

http://stackoverflow.com/questions/30346698/bootstrap-star-rating-shown-two-times

**Comment by kartik-v** [comment]
Check [comment & response on SFO](http://stackoverflow.com/questions/30346698/bootstrap-star-rating-shown-two-times/30414608#30414608).

**Comment by s1mp1c** [comment]
Thank you so much ;)
