### ISSUE TITLE
How to get value number selected by user for POST request?

### ISSUE THREAD

**Issue by s1mp1c** [kartik-v/bootstrap-star-rating#55]
I use the star rating within a form as an input to process with POST.
How to get the rating value number selected by user?

When i click on submit it get "undefined".

Here is my jQuery code:

$(document).ready(function() {
    $("#addReview").submit(function() {

        var vote = $("#inputRating").val();
        var review = $("#inputReview").val();
        
        $.post("add.php", { vote: vote, comment: review}, function(data) {
            var result = $.parseJSON(data);
            if (result.error) {
                $('#inputReview').css({"border": "2px solid red", "box-shadow": "0 0 3px red"});
            } else {
                $('#inputReview').css({"border": "2px solid blue", "box-shadow": "0 0 3px blue"});
            }
        });
        event.preventDefault();
    });
});

And here is my HTML form:

                    <form class="form-horizontal" id="addReview">
                      <div class="form-group">
                        <label for="inputRating" class="control-label col-xs-2">Vote</label>
                        <div class="col-xs-10">
                          <input class="rating" data-min="0" data-max="5" data-step="1" data-size="xs" data-show-clear="false" data-show-caption="false" required>
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="inputReview" class="control-label col-xs-2">Comment</label>
                        <div class="col-xs-10">
                          <textarea rows="5" class="form-control" id="inputReview" required></textarea>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-xs-offset-2 col-xs-10">
                          <button type="submit" class="btn btn-primary">Send</button>
                        </div>
                      </div>
                    </form>

PS: "required" attribute seems not to work with rating input. Is it a bug?
PPS: what is the difference between "data-disabled" and "data-readonly" attributes. Anyway how do I get rid of the hover mouse icon?

**Comment by kartik-v** [comment]
The plugin hides the input. Not sure if `required` attribute will be necessarily validated if input is hidden. Secondly note the the `min` and `max` settings for the plugin. Note that the [clearValue](http://plugins.krajee.com/star-rating#option-clearValue) setting is also important as this will set a value even if the input if cleared. This defaults to `min` as highlighted in docs. You may need to do [some reading of plugin options in the docs](http://plugins.krajee.com/star-rating#options).

`disabled` and `readonly` are obvious. They are similar to HTML default `disabled` and `readonly` attribute properties (both do not allow editing from frontend... but `readonly` allows you to set a value via javascript).

**Comment by s1mp1c** [comment]
In my code id="inputRating" was missing! Now it works!
Anyway i can't use "required". You could add an improvement for your plugin to manage required attribute ;)

**Comment by kartik-v** [comment]
For required attribute refer #52
