### ISSUE TITLE
Not rated is setting 1 instead of o

### ISSUE THREAD

**Issue by Nezam** [kartik-v/bootstrap-star-rating#56]
Relevant code:

```
 $("#input-rate").rating({
                starCaptions: { 0:"Not Rated",1: "Very Poor", 2: "Poor", 3: "Ok", 4: "Good", 5: "Very Good" },
                starCaptionClasses: { 1: "text-danger", 2: "text-warning", 3: "text-info", 4: "text-primary", 5: "text-success" }
            });
```
When initialized it works as expected.But when the value of the rating is changed and then the (-) button is used,the minimum value defaults to 1 instead of being 0

**Comment by kartik-v** [comment]
Please read the docs.

You need to specify the [clearValue setting](http://plugins.krajee.com/star-rating#option-clearValue) if you want it different than your `min` value. 

As highlighted in docs, if you do set `clearValue` it defaults to your `min` value. I presume your `min` rating value is `1` and if you need to set it to `0` or whatever you want on clearing the rating then set the `clearValue` appropriately.
