### ISSUE TITLE
How to get value of <input> with JSF framwork

### ISSUE THREAD

**Issue by facilus** [kartik-v/bootstrap-star-rating#57]
Hello,

Thank's for your plugin, i want to integrate it in jsf (j2ee) project

i want to know how to get value of the input in backing bean ?

thank's

**Comment by kartik-v** [comment]
Just read the HTML input value.

```js
$("#input-id").val(); // where `input-id` is the HTML ID attribute of the input element on which you initialized the rating
```

**Comment by kartik-v** [comment]
Just read the HTML input value.

```js
$("#input-id").val(); // where `input-id` is the HTML ID attribute of the input element on which you initialized the rating
```

If you are using HTML form based submission this should appear in your form POST data just like any other HTML form input.
