### ISSUE TITLE
"String.prototype.replaceAll" messing up with "jQuery.params"

### ISSUE THREAD

**Issue by iTouchTheSky** [kartik-v/bootstrap-star-rating#59]
Hi there, just found a glitch.

With your prototype added to the string, when using `jQuery.params`, it gives this : 
`star-rating.js:14 Uncaught TypeError: Cannot read property 'split' of undefined`

Checking the backtrace, this got called by `jQuery.params` when trying to do the following code : 
`add = function( key, value ) {`
`       // If value is a function, invoke it and return its value`
`       value = jQuery.isFunction( value ) ? value() : ( value == null ? "" : value );`
`       s[ s.length ] = encodeURIComponent( key ) + "=" + encodeURIComponent( value );`
`};`

It's detecting the string as an object with a function interpreting it's results.

So please, don't use prototypes on string, use a local function or fix it somehow

**Comment by kartik-v** [comment]
Resolved via 1016d46.
