### ISSUE TITLE
"showClear" and "showCaption" seem not to be working when they are as data values

### ISSUE THREAD

**Issue by glendel** [kartik-v/bootstrap-star-rating#62]
Hello, Great tool! Thanks for it!

It seems that when you have something like :

```html
<input type="text" id="" value="2.0" class="rating form-control hide" data-disabled="true" data-showclear="false" data-showcaption="false" data-size="xs">
```

All the other data options seem to be working as they must, except the `showClear` and `showCaption` options.

I double checked the JS file but sadly I was not able to find out the issue.

Please could you double check and let me know how could I make this works.

Thanks,

Kind regards,

Glendel

**Comment by kartik-v** [comment]
You are using it wrongly. it should be `data-show-clear` and `data-show-caption` when converted to data attributes.
