### ISSUE TITLE
bower, boostrap 4 apha bc-breaks

### ISSUE THREAD

**Issue by songoo** [kartik-v/bootstrap-star-rating#65]
This is pretty frequent now :

"bootstrap": ">= 3.0.0"

Is causing boostrap 4 being downloaded, boostrap 4 is not compatible with boostrap 3.* , should be "~3.0" i guess ?

**Comment by songoo** [comment]
Tnx very much, please add release so it can be found on http://www.webjars.org/ .

**Comment by songoo** [comment]
Any ETA on date of new release :?) .

**Comment by kartik-v** [comment]
New release "Version 3.5.4"  is tagged.
