### ISSUE TITLE
Mouse shift when hovering

### ISSUE THREAD

**Issue by dfabreguette-ap** [kartik-v/bootstrap-star-rating#66]
![capture d ecran 2015-09-18 a 15 42 59](https://cloud.githubusercontent.com/assets/7055931/9960638/f92b291a-5e1b-11e5-9d57-9e4110d1b42e.png)

Hi, 
Getting a shift between mouse position when hovering and effective rate.

Here's my config
```
...rating({
    min: 1,
    max: 5,
    step: 1
    });
```

At first, I though it was one of my CSS rules conflicting with the plugin but as I digged it in deeper, I noticed javascript calculated width of the colored stars element is set to 50% for a 3/5 rate (which should be 60% right ?).
![capture d ecran 2015-09-18 a 15 48 24](https://cloud.githubusercontent.com/assets/7055931/9960754/c3cd5c38-5e1c-11e5-80ff-236a1f252ed8.png)

Is this a real bug ?

**Comment by kartik-v** [comment]
No you need to understand it correct. Set min value = 0 and you should be fine. Min value corresponds to zero stars which means no stars selected.

**Comment by dfabreguette-ap** [comment]
Allright works fine :+1: 
Sorry !
