### ISSUE TITLE
change of stars and put images

### ISSUE THREAD

**Issue by Raman16** [kartik-v/bootstrap-star-rating#67]
Hi kartik v,
its a great plugin for my rating system..thanks for it.....but  i want to little modification like
i have two images with bulb on and bulb off..when mouse hover i need bulb on and when normal bulboff effect..how can i replace these images in place of those stars..please let me know...thanks in advance...

**Comment by wkf928592** [comment]
I encountered the same problem, how to solve ah?

**Comment by kartik-v** [comment]
You cannot use images - as the plugin relies on font symbols. If you have a font that renders this you can use them.
