### ISSUE TITLE
how could I hide the clear button and  issue

### ISSUE THREAD

**Issue by wormlxd** [kartik-v/bootstrap-star-rating#68]
how could I hide the clear button and  issue
![image](https://cloud.githubusercontent.com/assets/5212128/10414571/7aa88cd2-700d-11e5-8a85-d19a7f2fa984.png)
![image](https://cloud.githubusercontent.com/assets/5212128/10414572/806a6ed8-700d-11e5-89d6-aef590841be6.png)

**Comment by kartik-v** [comment]
By reading documentation. Go through the plugin options and settings - you can set `showClear` property [as mentioned in the docs](http://plugins.krajee.com/star-rating#option-showClear).

**Comment by wormlxd** [comment]
Thanks ,because of I use wrong id="text",so,the data-showClear="false"  did not effective
