### ISSUE TITLE
Problem with touchmove value triggering

### ISSUE THREAD

**Issue by Ljudevit** [kartik-v/bootstrap-star-rating#69]
Hello,

first of all, thank you very much for really great plugin! 

But I have a question regarding touch dragging on stars and value update. I realized that caption values are updated on each pass with finger and are stopped on value when touch is released. However, input value is not changing in the same way and is remembering only a value on touchstart. 

How can I also update input value in the same way as caption value while touch dragging?

Any help would be much appreciated!

**Comment by wkf928592** [comment]
I encountered the same problem, how to solve ah?

**Comment by Ljudevit** [comment]
Well, what did the trick for us is to add this under line 170:

self.$caption.html(caption);
self.$stars.css('width', width);
self.setStars(pos); 

Basically, what that did is that input was updated on touchend as well.

**Comment by niniks** [comment]
I'm having sort of the same problem, the touch clicks are measured but when using a full swipe from start till end it doesnt, im running the 3.5.5 version and this only occurs on ipad (touch devices)

**Comment by zhourunlai** [comment]
thanks @niniks 

change 

>  click touchstart

to

>  click touchstart touchmove touchend

in line 78

**Comment by kartik-v** [comment]
Check if latest release v3.5.6 resolves your case.
