### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by musicformellons** [kartik-v/bootstrap-star-rating#70]
Everything works, except I get in the Console:
Uncaught TypeError: Cannot read property 'pageX' of undefined

It appears in star-rating.js line 76, which is the second line of:

        getPosition: function (e) {
            var pageX = e.pageX || e.originalEvent.touches[0].pageX;
            return pageX - this.$rating.offset().left;
        },

Furthermore:
Rating.getPosition	@	star-rating.js:76
Rating.setTouch	@	star-rating.js:160
(anonymous function)	@	star-rating.js:177
m.event.dispatch	@	jquery-1.11.3.min.js:4
r.handle	@	jquery-1.11.3.min.js:4

I made a fiddle of it which has same issue:
http://jsfiddle.net/musicformellons/dpnrgdk3/

**Comment by bgaillard** [comment]
Hi, I think this should be fixed with https://github.com/kartik-v/bootstrap-star-rating/pull/72.

**Comment by musicformellons** [comment]
@bgaillard Indeed solved now! Thanks!
