### ISSUE TITLE
Latest release 3.5.5 is not available on bower

### ISSUE THREAD

**Issue by satyapatidar** [kartik-v/bootstrap-star-rating#73]
Kartik,

You might need to create a new release for 3.5.5?

bower install gives these errors:

bower bootstrap-star-rating#3.5.5 not-cached git://github.com/kartik-v/bootstrap-star-rating.git#3.5.5
bower bootstrap-star-rating#3.5.5 resolve git://github.com/kartik-v/bootstrap-star-rating.git#3.5.5
bower bootstrap-star-rating#3.5.5 ENORESTARGET No tag found that was able to satisfy 3.5.5

Additional error details:
Available versions in git://github.com/kartik-v/bootstrap-star-rating.git: 3.5.4, 3.5.3, 3.5.2, 3.5.1, 3.5.0, 3.4.0, 3.3.0, 3.2.0, 3.1.0, 3.0.0, 2.6.0, 2.5.0, 2.0.0, 1.2.0

**Comment by kartik-v** [comment]
This release will be tagged a bit later. You could directly fetch from dev-master for now.

**Comment by joomlaA1** [comment]
hello @kartik-v
sry can u... https://github.com/kartik-v/yii2-krajee-base/issues/45
thanks...

**Comment by bgaillard** [comment]
Hi @kartik-v, is it possible to create the tag for version `3.5.5`. 

Using "absolute" git URLs works under our development environments but not in our staging server...

```
bower bootstrap-star-rating#a749b64ba806c0cd0d60de3b78761f27e6d401bc          ECMDERR Failed to execute "git clone git@github.com:gomoob/bootstrap-star-rating.git /tmp/523df52d8a199b1662fcb27d96af5840/bower/bootstrap-star-rating-266-RdMyis --progress", exit code of #128  (ssh-askpass:376): Gtk-WARNING **: cannot open display: :99 Host key verification failed. fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.
```

Why do you need to wait before creating this tag ?

**Comment by wli** [comment]
@bgaillard did you try using the https version of the git url?

`"bootstrap-star-rating": "https://github.com/kartik-v/bootstrap-star-rating.git#e78f3288aaa592cc868a6625970c74b973e815fc",`

**Comment by bgaillard** [comment]
Hi @wli, thanks for the suggestion, I'm already using the https URL :-(

**Comment by bgaillard** [comment]
@kartik-v Thanks for the tagging, our builds work now :+1:
