### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pageX' of undefined

### ISSUE THREAD

**Issue by bgaillard** [kartik-v/bootstrap-star-rating#77]
Hi, since version 3.5.5 we encounter a new `Uncaught TypeError: Cannot read property 'pageX' of undefined` error.

This is easy to replay by opening Chrome Dev Tools with mobile device emulation on the demo http://plugins.krajee.com/star-rating/demo.

The error appears here https://github.com/kartik-v/bootstrap-star-rating/blob/master/js/star-rating.js#L96.

When we touch the widget it appears the `getPosition(e)` method is called several times, when the `touchend` event arrives the `e` argument is `undefined`.

How can we quickly fix this error ?

**Comment by kartik-v** [comment]
Try to replace the line 96

FROM
```js
 var pageX = isEmpty(e.pageX) ? e.originalEvent.touches[0].pageX : e.pageX;
```

TO 
```js
 var pageX = e.pageX || e.originalEvent.touches[0].pageX`;
```

and update if it works.

**Comment by bgaillard** [comment]
Hi @kartik-v and thanks for your quick response on this. 

Calling `e.something` will not work because the problem here is that `e` is `undefined` when the event encountered is a `touchend` event.

I do not understand every subtilities in the source code, I tried to update `touches = isEmpty(ev.touches) ? ev.touches : ev.changedTouches` without success.

Perhaps the problem is not inside `getPosition(e)` but before calling it ?

**Comment by kartik-v** [comment]
The only maor difference between 3.5.5 and earlier version was the code I posted above... so if it was working earlier for you - then not sure why it does not work now.

**Comment by kartik-v** [comment]
Try changing [Line 185](https://github.com/kartik-v/bootstrap-star-rating/blob/master/js/star-rating.js#L185) to the following and update if it works:

```js
touches = ev.touches.length > 0 ? ev.touches : ev.changedTouches
```

**Comment by bgaillard** [comment]
It does not work either, in this case I don't know why but our code falls inside an infinit loop (its calling the `rating.change` event callback function again an again). 

Don't know what's going on exactly but it seems the bug is linked to the sequence of touch events fired.  If I add a break point inside a `rating.change` callback function then the error is not encountered.
