### ISSUE TITLE
Bad behavior when min is set

### ISSUE THREAD

**Issue by bgaillard** [kartik-v/bootstrap-star-rating#78]
Hi, we encounter a strange behavior when the `min` parameter is set using Javascript. 

Here is a JSFiddle to show it http://jsfiddle.net/bgaillard/rm42t0tt (this uses the Star Rating JS files of the demo). 

Look at the stars, we use a `step` parameter which is equal to `1` and under Chrome we see strangely filled stars.

Also, if Chrome Dev tools are opened and mobile device emulation mode is set it is possible to set `0` star even if the `min` parameter is equal to `1`.

**Comment by kartik-v** [comment]
Have explained this before... and you need to understand this correctly.

For your use case, YOU MUST set `min = 0` and it will be fine. 

NOTE that the value of rating depends on 
- the `min` value - which is the value when NO STARS are selected
- the `max` value - which is the value when ALL STARS are selected
- the `step` to increment
- and the last one MOST IMPORTANT - the `number of stars`.

So why you are facing the situation for your use case is that you have 5 stars with `min = 1` and `max = 5` so each increment will highlight 1.2 stars.

**Comment by bgaillard** [comment]
@kartik-v Ok I understand it, setting `min = 0` and `max = 5` fixed the display.

But with those values it seems to be possible to set 0 star on touch devices (with the mouse it works and we cannot set less than 1 star). 

Is it the expected behavior on touch devices ? 

Perhaps its linked to the other issue I've posted today https://github.com/kartik-v/bootstrap-star-rating/issues/77 ?

Thanks

**Comment by kartik-v** [comment]
You need to click the clear button to clear all stars.

**Comment by bgaillard** [comment]
> You need to click the clear button to clear all stars.

@kartik-v I do not want to clear all stars and i'm not using the clear button (its disabled / hidden).

> it seems to be possible to set 0 star on touch devices

IMO its a bug, did you try it with a touch device ? 

To see this "bug" go to http://jsfiddle.net/bgaillard/rm42t0tt, open Google Chrome dev tools and choose a mobile device (Google Nexus 10 for example). 

* Then with touch emulation enabled set for example 2 stars, ok
* Now keep the mouse down on the widget (i.e simulates a "long touch") and make it slide to the left until the widget has no star, then release the mouse (i.e simulates a touch end)

The end result is that on touch device the Widget can be set (not reset) to 0 star, is it expected ?

After more testing it also appears that on touch device the `rating.change` event is fired on first touch and not when the figer is released from the screen. 

If you touch star 5 and keep your finger pressing the screen, then if you release your finger on star 1 the end result is that graphically the widget displays one star but the `rating.change` event fired value `5` (i'll try what you propose in issue https://github.com/kartik-v/bootstrap-star-rating/issues/77 to see if the problem is not linked to the `pageX` undefined error).
