### ISSUE TITLE
FontAwesome Icons Doesnt work.

### ISSUE THREAD

**Issue by ronakjain90** [kartik-v/bootstrap-star-rating#79]
Hi,

I guess something broke. I'm using 

bootstrap-star-rating : 3.5.5
Font Awesome : 4.4.0
jQuery : 1.11.0
bootstrap : 3.3.5

I'm loading Font Awesome and jQuery using CDN. boostrap and bootstrap-star-rating is served by application 

The below HTML Snippet, load plain symbol "&#xf164;"

```
input id="input-20b" class="rating" data-size="xl" data-symbol="&#xf164;" data-glyphicon="false" 
    data-rating-class="rating-fa" data-default-caption="{rating} likes" data-star-captions="{}"
```

Default star Symbol works. Is it something that i'm missing. Looks straight forward though.

**Comment by ronakjain90** [comment]
Okay,

I Tried to do the same using JS Fiddle, https://jsfiddle.net/sf0epafp/1/

It works, I guess something in rails application is converting the symbol ```"&#xf164;"``` to text.

Any Clue whats going wrong.?

**Comment by kartik-v** [comment]
You need to check this in your server code.

Alternatively you can also initialize the same via javascript (the symbol code will be different for JS versus HTML5 data attribute ). You must set the unicode character code. [Font Awesome coffee example in advanced usage](http://plugins.krajee.com/star-rating/demo#advanced-usage) for initialization via javascript.

Secondly the **ratingClass** is important for font awesome as mentioned in the example.
