### ISSUE TITLE
data-showClear and data-showCaption ignored

### ISSUE THREAD

**Issue by Fuzzyma** [kartik-v/bootstrap-star-rating#80]
... and many other options you can pass to the jquery-constructor.
Following bootstraps api, every option should be available in the markup, too so you dont have to touch a scriptfile.
I would be glad to see this in the next version :)

**Comment by kartik-v** [comment]
Check if you are passing it wrongly. When passing plugin properties via HTML5 data attributes... you must convert camel case characters to hyphenated attributes.

- So `showClear` will become `data-show-clear`
- and `showCaption` will become `data-show-caption`
