### ISSUE TITLE
Problem with locales

### ISSUE THREAD

**Issue by wowkin2** [kartik-v/bootstrap-star-rating#85]
I use Ukrainian locale. On the event "OnClear" caption changes to the English "Not Rated".
I tried to use other available languages and got the same.
Perhaps "Not Rated" is hardcoded somewhere.

**Comment by kartik-v** [comment]
Just setting the language will not work. Read docs.

You need to also load the locale specific js file [as mentioned in the translations section of the docs](http://plugins.krajee.com/star-rating#translations).

You can submit a pull request for the translation for your language (UKRANIAN) if it does not exist.

**Comment by kartik-v** [comment]
You need to set the [language property](http://plugins.krajee.com/star-rating#option-language) and load the right JS file. Note that just setting the language property will not work. Read docs.

You need to also load the locale specific js file [as mentioned in the translations section of the docs](http://plugins.krajee.com/star-rating#translations).

You can submit a pull request for the translation for your language if it does not exist. You can check this and let know.

**Comment by wowkin2** [comment]
I already did pull request, and you accepted it.
Language module works correctly in all cases except for:
> On the event "OnClear" caption changes to the English "Not Rated".
The same I can see for all other languages.

**Comment by jcarlos37** [comment]
I used these parameters:

```
 StarRating::widget([
 'name' => 'rating_article',
 'value' => 3,
 'language' => 'es',
 'pluginOptions' => [
 'size' => 'xs',
 'language' => 'es',
 ],
 ]);
``` 

But did not work.

Finally, I need to fix the file vendor\kartik-v\yii2-widget-rating\StarRating.php (version 1.0.2), the line 60 was replaced:

```
//StarRatingAsset::register($view)->addLanguage($this->language, 'star-rating_locale_'); //Old line
StarRatingAsset::register($view)->addLanguage($this->language, null, 'js/locales'); //New line
```
