### ISSUE TITLE
Star rating not working with .clone() in jquery

### ISSUE THREAD

**Issue by hoangphucvu** [kartik-v/bootstrap-star-rating#93]
I have div like this and the button to clone that div
```
<div class="sectionContent" id="skill">
                    <article class="skill">
                        <span contenteditable>-PHP</span>
                        <input class="rating" data-show-clear="false" data-show-caption="true" data-size="xs" data-show-caption="true" data-step="1">
                    </article>
                </div>
 <input type="button" class="btn btn-primary btn-xs clone" value="Clone" id="btnAddSkill">
```
js 
```
$('#btnAddSkill').click(function() {
    $('.skill:first').clone().appendTo("#skill");
});
```
In the clone element i can't click on the star to rate it.So how can i fix this.Thanks for your help

**Comment by kartik-v** [comment]
Please use the [webtips Q & A forum](http://webtips.krajee.com/questions) for programming help and questions. Use the repo only for reporting bugs and enhancements.

For your use case - you need to reinitialize the plugin after clone.
