### ISSUE TITLE
The filled stars on RTL Ratings appear to jitter when animated.

### ISSUE THREAD

**Issue by davidklebanoff** [kartik-v/bootstrap-star-rating#97]
The filled stars on RTL Ratings appear to jitter (shake) when animated. It appears to be on all themes and I can reproduce it the latest versions of Chrome and Firefox - Chrome is a bit more obvious.

At a quick glance it appears to be the `transform: matrix(-1,0,0,1,0,0);` that's causing the issue.

**Comment by kartik-v** [comment]
Yes you cannot avoid the transform... its needed only for RTL inputs to mirror flip it [read about the fineprint in `rtl` setting](http://plugins.krajee.com/star-rating#option-rtl).

**Comment by kartik-v** [comment]
An enhancement for this could be to make `transition animation` optional.

**Comment by davidklebanoff** [comment]
You move too fast!

There seems to be fixes for Webkit, but I haven't gotten anything to work in Firefox just yet:

http://stackoverflow.com/questions/3461441/prevent-flicker-on-webkit-transition-of-webkit-transform

For example, setting `transform: matrix(-1,0,0,1,0,0) translate3d(0,0,0);` on `.rating-rtl .filled-stars` seems to address the issue in Chrome.

**Comment by kartik-v** [comment]
Fixed the CSS.
