### ISSUE TITLE
Not working with rtl

### ISSUE THREAD

**Issue by stepanorda** [kartik-v/bootstrap-star-rating#98]
I'm using your yii2 rating widget for site in Hebrew. Until i set rtl everything was working. But now it looks like this:
![2016-02-18 20 36 00](https://cloud.githubusercontent.com/assets/6368917/13153964/4f1a2c14-d67f-11e5-842f-c8c1d05a2e83.png)

My code: `<?= $form->field($model, 'rate')->widget(StarRating::classname(), ['pluginOptions' => ['step' => 0.5, 'showClear' => false, 'showCaption' => false, 'size' => 'xs','rtl'=>true]]) ?>`

The bug is appearing when I add `dir="rtl"` to `<html>` tag.

**Comment by kartik-v** [comment]
Read docs. Updated release v4.x has BC breaking changes. You need to check for config changes if any and most importantly clean up browser cache or stale assets on your environment to ensure you are running updated code.

**Comment by stepanorda** [comment]
First of all the last version was the first for me, I didn't migrate from previous, so BC doesn't apply to my situation. Second - cleared cache, reinstalled module, checked config. The problem remains. And only appears when I set rtl in html tag.

**Comment by kartik-v** [comment]
I still feel u have a old version. Because when I see the image you posted... It has grey filled star which has been replaced with an empty star since v4 of bootstraps star rating. You can try to overwrite this plugin folder with latest from github and check for yourself. Another note on RTL input... It floats the widget to the right. So include a div clearfix after the rating.

**Comment by stepanorda** [comment]
Ok actually there was an old version of bootstrap-star-rating for some reason composer fetched the old one (the yii2-widget-rating was the last one). But after update nothing changed except the form of the stars. Added clearfix, purged assets folder, cleared cache. All the same. Manually downloaded bootstrap-star-rating files from github - allso no change. Here is the working example http://pendel.xyz/site/test/ when remove dir="rtl" for test from html tag, everything is working fine.

**Comment by kartik-v** [comment]
The CSS Transition (transform) is not working for your use case... you may want to debug as I am not sure why it should not...

**Comment by kartik-v** [comment]
Its your bootstrap-theme.css.

Disable it and it should work fine... I just tested it through the console.

**Comment by kartik-v** [comment]
It is the  `html dir = "rtl"` I suppose... it is causing the transform to reverse itself...

**Comment by kartik-v** [comment]
You need to wrap your Rating widget inside a `div` container with `dir = ltr` and it will work.

For example:

```php
<div dir="ltr">
   <?php echo StarRating::widget(['options'=>['dir'=>'rtl']]);
</div>
```

**Comment by kartik-v** [comment]
If you are using a plain `html dir="rtl"` then you can directly use a normal LTR rating... with `rtl` = `false`

**Comment by stepanorda** [comment]
Thank you, workaround with div with ltr worked fine.
